name: Smoke Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  smoke-test:
    runs-on: 4-core-ubuntu-gpu-t4

    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v3
    
    - name: Set up Python
      run: uv python install
    
    - name: Install package and dependencies
      run: uv sync --dev
    
    - name: Clone FACTO source
      run: git clone https://github.com/pytorch-labs/FACTO.git
    
    - name: Build and install FACTO
      run: cd FACTO && uv pip install .
    
    - name: Run smoke test
      run: | 
        uv run python -m BackendBench.scripts.main --suite smoke --backend aten 
        echo "OUTPUT_DIR=$(grep -oP 'Results saved to directory: \K.*' smoke.log | tail -1)" >> $GITHUB_ENV
    
    - name: Check smoke test failures
      run: |
        if [ -s "$OUTPUT_DIR/failed_ops.json" ]; then
          echo "Some operations failed in the smoke test."
          cat "$OUTPUT_DIR/failed_ops.json"
          exit 1
        else
          echo "All operations passed the smoke test."
        fi
    
    - name: Run opinfo test
      run: |
        uv run python -m BackendBench.scripts.main --suite opinfo --backend aten
        echo "OUTPUT_DIR_OPINFO=$(grep -oP 'Results saved to directory: \K.*' opinfo.log | tail -1)" >> $GITHUB_ENV

    - name: Check opinfo test failures
      run: |
        if [ -s "$OUTPUT_DIR_OPINFO/failed_ops.json" ]; then
          echo "Some operations failed in the opinfo test."
          cat "$OUTPUT_DIR_OPINFO/failed_ops.json"
          exit 1
        else
          echo "All operations passed the opinfo test."
        fi

    - name: Run FACTO test
      run: uv run python -m BackendBench.scripts.main --suite facto --backend aten --ops "add.Tensor" 
    
    - name: Run pytest tests
      run: uv run pytest test/
